---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/categories":
    get:
      summary: list categories
      tags:
        - Category
      responses:
        '200':
          description: successful
    post:
      summary: create category
      tags:
        - Category
      parameters: [ ]
      responses:
        '201':
          description: category created
        '422':
          description: invalid request
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
                - name
  "/categories/{id}":
    parameters:
      - name: id
        in: path
        description: id
        required: true
        schema:
          type: string
    get:
      summary: show category
      tags:
        - Category
      responses:
        '200':
          description: successful
    patch:
      summary: update category
      tags:
        - Category
      responses:
        '200':
          description: successful
    put:
      summary: update category
      tags:
        - Category
      responses:
        '200':
          description: successful
    delete:
      summary: delete category
      tags:
        - Category
      responses:
        '200':
          description: successful
servers:
  - url: https://{defaultHost}
    variables:
      defaultHost:
        default: www.example.com
