---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/categories":
    get:
      summary: list categories
      tags:
      - Category
      responses:
        '200':
          description: successful
    post:
      summary: create category
      tags:
      - Category
      parameters: []
      responses:
        '201':
          description: category created
        '422':
          description: invalid request
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/categories/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show category
      tags:
      - Category
      responses:
        '200':
          description: successful
    patch:
      summary: update category
      tags:
      - Category
      responses:
        '200':
          description: successful
    put:
      summary: update category
      tags:
      - Category
      responses:
        '200':
          description: successful
    delete:
      summary: delete category
      tags:
      - Category
      responses:
        '200':
          description: successful
  "/products/{product_id}/general_specifications":
    parameters:
    - name: product_id
      in: path
      description: product_id
      required: true
      schema:
        type: string
    get:
      summary: list general_specifications
      tags:
      - General Specification
      responses:
        '200':
          description: successful
    post:
      summary: create general_specification
      tags:
      - General Specification
      parameters: []
      responses:
        '201':
          description: general specification created
        '422':
          description: invalid request
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                release_date:
                  type: string
                general:
                  type: string
              required:
              - release_date
              - general
  "/products/{product_id}/general_specifications/{id}":
    parameters:
    - name: product_id
      in: path
      description: product_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show general_specification
      tags:
      - General Specification
      responses:
        '200':
          description: successful
    patch:
      summary: update general_specification
      tags:
      - General Specification
      responses:
        '200':
          description: successful
    put:
      summary: update general_specification
      tags:
      - General Specification
      responses:
        '200':
          description: successful
    delete:
      summary: delete general_specification
      tags:
      - General Specification
      responses:
        '200':
          description: successful
  "/categories/{category_id}/products":
    parameters:
    - name: category_id
      in: path
      description: category_id
      required: true
      schema:
        type: string
    get:
      summary: list products
      tags:
      - Product
      responses:
        '200':
          description: successful
    post:
      summary: create product
      tags:
      - Product
      parameters: []
      responses:
        '201':
          description: product created
        '422':
          description: invalid request
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
              required:
              - name
  "/categories/{category_id}/products/{id}":
    parameters:
    - name: category_id
      in: path
      description: category_id
      required: true
      schema:
        type: string
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show product
      tags:
      - Product
      responses:
        '200':
          description: successful
    patch:
      summary: update product
      tags:
      - Product
      responses:
        '200':
          description: successful
    put:
      summary: update product
      tags:
      - Product
      responses:
        '200':
          description: successful
    delete:
      summary: delete product
      tags:
      - Product
      responses:
        '200':
          description: successful
  "/reviews":
    get:
      summary: list reviews
      tags:
      - Review
      responses:
        '200':
          description: successful
    post:
      summary: create review
      tags:
      - Review
      parameters: []
      responses:
        '201':
          description: review created
        '422':
          description: invalid request
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                body:
                  type: string
                rate:
                  type: integer
                product_id:
                  type: string
              required:
              - title
              - body
              - rate
  "/reviews/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show review
      tags:
      - Review
      responses:
        '200':
          description: successful
    patch:
      summary: update review
      tags:
      - Review
      responses:
        '200':
          description: successful
    put:
      summary: update review
      tags:
      - Review
      responses:
        '200':
          description: successful
    delete:
      summary: delete review
      tags:
      - Review
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
